# Generated by Django 6.0.4 on 2026-04-23 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("hr", "HR"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("english", "English"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intern", "Intern"),
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                        ],
                        default="intern",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English")],
                        default="fr",
                        max_length=10,
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "final_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("question_count", models.PositiveSmallIntegerField(default=0)),
                ("max_questions", models.PositiveSmallIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("ai", "AI"), ("user", "User")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("improved_answer", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
